/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vista;

import controlador.Registro;
import javax.swing.JOptionPane;
import modelo.Libro;

/**
 *
 * @author Julio
 */
public class Agregar extends javax.swing.JFrame {

    /**
     * Creates new form Listar
     */
    public Agregar() {
        initComponents();
    }
    
    private void limpiar(){
        this.codigoTextBox.setText("");
        this.autorTextBox.setText("");
        this.isbnTextBox.setText("");
        this.nacionalidadTextBox.setText("");
        this.libroTextBox.setText("");
        this.ejemplaresTextBox.setText("");
        this.editorialTextBox.setText("");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        codigoTextBox = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        isbnTextBox = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        libroTextBox = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        ejemplaresTextBox = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        editorialTextBox = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        autorTextBox = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        nacionalidadTextBox = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        generoCombo = new javax.swing.JComboBox<>();
        temaCombo = new javax.swing.JComboBox<>();
        lectorCombo = new javax.swing.JComboBox<>();
        agregarLibro = new javax.swing.JButton();
        jLabel11 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Código");

        codigoTextBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                codigoTextBoxActionPerformed(evt);
            }
        });

        jLabel2.setText("ISBN");

        isbnTextBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                isbnTextBoxActionPerformed(evt);
            }
        });

        jLabel3.setText("Nombre Libro");

        libroTextBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                libroTextBoxActionPerformed(evt);
            }
        });

        jLabel4.setText("Número ejemplares");

        ejemplaresTextBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ejemplaresTextBoxActionPerformed(evt);
            }
        });

        jLabel5.setText("Genero");

        jLabel6.setText("Tema");

        editorialTextBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                editorialTextBoxActionPerformed(evt);
            }
        });

        jLabel7.setText("Nombre Autor");

        autorTextBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                autorTextBoxActionPerformed(evt);
            }
        });

        jLabel8.setText("Nacionalidad Autor");

        nacionalidadTextBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nacionalidadTextBoxActionPerformed(evt);
            }
        });

        jLabel9.setText("Nombre Editorial");

        jLabel10.setText("Tipo lector");

        generoCombo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Lirico", "Narrativa", "Drama" }));

        temaCombo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Policial", "Romantica", "Ciencia Ficcion", "Aventura", "Terror", "Investigacion", "Hogar" }));

        lectorCombo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Infantil", "Adulto" }));

        agregarLibro.setText("Agregar Libro");
        agregarLibro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                agregarLibroActionPerformed(evt);
            }
        });

        jLabel11.setText("Agregar Libro");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel1)
                                    .addComponent(jLabel2))
                                .addGap(206, 206, 206))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addComponent(jLabel3)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(codigoTextBox, javax.swing.GroupLayout.DEFAULT_SIZE, 129, Short.MAX_VALUE)
                                    .addComponent(isbnTextBox)
                                    .addComponent(libroTextBox))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 0, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel10)
                            .addComponent(jLabel9))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(editorialTextBox)
                            .addComponent(lectorCombo, 0, 130, Short.MAX_VALUE))
                        .addGap(71, 71, 71))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel7)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel8)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(nacionalidadTextBox, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(autorTextBox, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel4)
                                    .addComponent(jLabel5)
                                    .addComponent(jLabel6))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(ejemplaresTextBox)
                                    .addComponent(generoCombo, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(temaCombo, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(agregarLibro)
                        .addGap(97, 97, 97))))
            .addGroup(layout.createSequentialGroup()
                .addGap(240, 240, 240)
                .addComponent(jLabel11)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel11)
                .addGap(12, 12, 12)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(codigoTextBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(isbnTextBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(libroTextBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel9)
                    .addComponent(editorialTextBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(ejemplaresTextBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel10)
                    .addComponent(lectorCombo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(generoCombo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(temaCombo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel7)
                            .addComponent(autorTextBox, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(agregarLibro)
                        .addGap(18, 18, 18)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(nacionalidadTextBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(21, 21, 21))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void codigoTextBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_codigoTextBoxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_codigoTextBoxActionPerformed

    private void isbnTextBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_isbnTextBoxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_isbnTextBoxActionPerformed

    private void libroTextBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_libroTextBoxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_libroTextBoxActionPerformed

    private void ejemplaresTextBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ejemplaresTextBoxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ejemplaresTextBoxActionPerformed

    private void editorialTextBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editorialTextBoxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_editorialTextBoxActionPerformed

    private void autorTextBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_autorTextBoxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_autorTextBoxActionPerformed

    private void nacionalidadTextBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nacionalidadTextBoxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nacionalidadTextBoxActionPerformed

    private void agregarLibroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_agregarLibroActionPerformed
        Registro controlador = new Registro();
        char generoFinal, lectorFinal;
        int codigo = Integer.parseInt(this.codigoTextBox.getText());
        int isbn = Integer.parseInt(this.isbnTextBox.getText());
        String libro = this.libroTextBox.getText();
        int ejemplares = Integer.parseInt(this.ejemplaresTextBox.getText());
        String autor = this.autorTextBox.getText();
        String nacionalidad = this.nacionalidadTextBox.getText();
        String editorial = this.editorialTextBox.getText();
        String genero = (String) this.generoCombo.getSelectedItem();
        switch (genero) {
            case "Lirico":
                generoFinal = 'L';
                break;
            case "Narrativa":
                generoFinal = 'N';
                break;
            case "Drama":
                generoFinal = 'D';
                break;
            default:
                generoFinal = '-';
                break;

        }
        String tema = (String) this.temaCombo.getSelectedItem();
        String lector = (String) this.lectorCombo.getSelectedItem();
        switch (lector) {
            case "Infantil":
                lectorFinal = 'I';
                break;
            case "Adulto":
                lectorFinal = 'A';
                break;
            default:
                lectorFinal = 'A';
                break;

        }
        //int codigo, int isnb, String nombreLibro, int numEjemplares, char genero, String tema, String nombreAutor, String nacionalidadAutor, String nombreEditorial, char tipoLector
        
        if(controlador.agregar(codigo, isbn, libro, ejemplares,generoFinal, tema, autor, nacionalidad, editorial, lectorFinal)){
            JOptionPane.showMessageDialog(null, "Libro agregado correctamente");
            limpiar();
        }
        else
            JOptionPane.showMessageDialog(null, "Error al ingresar el libro");
    }//GEN-LAST:event_agregarLibroActionPerformed

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton agregarLibro;
    public javax.swing.JTextField autorTextBox;
    public javax.swing.JTextField codigoTextBox;
    public javax.swing.JTextField editorialTextBox;
    public javax.swing.JTextField ejemplaresTextBox;
    public javax.swing.JComboBox<String> generoCombo;
    public javax.swing.JTextField isbnTextBox;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    public javax.swing.JComboBox<String> lectorCombo;
    public javax.swing.JTextField libroTextBox;
    public javax.swing.JTextField nacionalidadTextBox;
    public javax.swing.JComboBox<String> temaCombo;
    // End of variables declaration//GEN-END:variables
}
